### ISSUE TITLE
User Feature Request: Alter image capture to analyse full resolution

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-frontend#144]
**Is your feature request related to a problem? Please describe.**
As currently constructed, the Nachet web app resizes the 1080p feed from the Tagarno camera to fit the view box on the app screen, then takes the capture which the model then analyzes from that smaller view box. As a result the images the app takes are only 971 x 584 pixels, roughly half of the original 1920 x 1080. This reduction in pixels relative to the training images reduces the number of pixels in each seed image for the model to analyze, makes the captured images less similar to the images used to train the model, and can be expected to reduce accuracy.

**Describe the solution you'd like**
It would be better to take the capture for the model from a full-sized version of the camera feed, then reduce/render that to fit the box in the app for results display purposes only.

**Additional context**
Joseffus seemed to have some good ideas about how this could be done, I hope he can address the issue more clearly than I have 😄

**Comment by ChromaticPanic** [comment]
The issue is that the microscope feed is bound to the canvas size which is proportional to the size of your browser window. Then the save function saves this scaled image. 

If the need is urgent quickest way around this is to simply use a higher resolution monitor, 1440p or 4k would allow the browser and canvas to easily have more than 1920x1080 pixels.

There are a few options to fix this in code.  We could try using a hidden high res canvas for saving images and sending for inference. Or imageCapture grabFrame() takePhoto() browser functions (experimental) https://webrtchacks.com/still-image-from-webcam-stream-approaches/

**Comment by ChromaticPanic** [comment]
I used OBS as a cam source to stream these images. We see the after image has 1920x1080 resolution. Now I don't know if the microscope source has higher than 1920x1080 resolution because we can use the maximum resolution provided by the image source. e.g. a 4K camera will have 3840x2160 pixels

This first one is before the fix I implemented
![testforcetrue-2024-5-7](https://github.com/ai-cfia/nachet-frontend/assets/78883122/8172a84d-1669-461f-ad65-dfeb232b6047)


This one is after
![testforcetrue2-2024-5-7](https://github.com/ai-cfia/nachet-frontend/assets/78883122/e9870208-4262-47b8-99e4-e3a5dd973f63)

**Comment by ChromaticPanic** [comment]
Not sure if this also fixes #54 . I don't have a microscope to check 😅

**Comment by TaranMeyer** [comment]
Oh this is awesome!!!! I will do some checking today!

**Comment by ChromaticPanic** [comment]
> Oh this is awesome!!!! I will do some checking today!
> 
> ... I guess I jumped the gun gain, it doesn't look like there's a change on the front end yet? 🤣

I think your interface is still on 0.4.0 ? We are actually on 0.8.0 now, I think there may be deployment issues as well. I brought it up at today's scrum since the endpoint Liang is using is on 0.2.0 .

**Comment by ChromaticPanic** [comment]
> Yes, mine says 0.4.0 for sure. Is there a way I can fix that, or a different link I should be using? Refreshing the page doesn't seem to do it, though I suppose I haven't cleared my browser cache.

It has to do with the deployment pipeline. I haven't looked that far into it but the devOps team should be able to figure it out easily.
