### ISSUE TITLE
Create docker file and instructions to build a docker for nachet-frontend

### ISSUE THREAD

**Issue by aakritimadaan** [ai-cfia/nachet-frontend#36]
Create a docker and instructions to build a docker for nachet-frontend with same configuration, as we have docker file for louis-frontend and finesse-frontend.

**Comment by MaxenceGui** [comment]
This issue seems to be completed with a docker file on Nachet front end main being present and a [Deployement Environment Configuration Management file](https://github.com/ai-cfia/dev-rel-docs/blob/103-documentation-request-environment-configuration-guidelines/TypeScript-AppVersion/DEPLOYMENT_ENV_CONFIG_MANAGEMENT.md) in dev-rel-docs.
